[package]
name = "puppeter"
version = "0.1.0"
edition = "2021"

[dependencies]
puppeter-derive = { path = "./puppeter-derive", optional = true }
rayon = { version = "1.8.0", optional = true }
pollster = { version = "0.3.0", optional = true }
ahash = "0.8"
async-trait = "0.1"
hashbrown = "0.14"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.32", features = ["full"] }
tracing = "0.1"
indexmap = "2.0.2"

[dev-dependencies]
minions-derive = { path = "./minions-derive" }
actix = "0.13.1"
vin = "9.1"
ractor = "0.9"
criterion = "0.5"
coerce = "0.8.10"

[features]
derive = ["dep:minions-derive"]
rayon = ["dep:rayon", "dep:pollster"]

[[bench]]
name = "minions_bench"
harness = false

[[bench]]
name = "tokio_bench"
harness = false

[[bench]]
name = "actix_bench"
harness = false

[[bench]]
name = "vin_bench"
harness = false

[[bench]]
name = "ractor_bench"
harness = false

[[bench]]
name = "coerce_bench"
harness = false

[profile.bench]
debug = true
