[package]
name = "master-of-puppets"
version = "0.1.0"
edition = "2021"

[dependencies]
master-of-puppets-derive = { path = "./master_of_puppets_derive", optional = true }
stream-punk = { path = "../stream-punk/", optional = false }
rayon = { version = "1.8.0", optional = true }
async-trait = "0.1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.32", features = ["full"] }
tracing = "0.1"
indexmap = "2.0.2"
rustc-hash = "1.1.0"
anyhow = "1.0.75"
async-recursion = "1.0.5"

[dev-dependencies]
master-of-puppets-derive = { path = "./master_of_puppets_derive" }
actix = "0.13.1"
vin = "9.1"
ractor = "0.9"
criterion = "0.5"
coerce = "0.8.10"

[features]
derive = ["dep:master-of-puppets-derive"]
punk = ["dep:stream-punk"]
rayon = ["dep:rayon"]

[[bench]]
name = "master_of_puppets_bench"
harness = false

[[bench]]
name = "tokio_bench"
harness = false

[[bench]]
name = "actix_bench"
harness = false

[[bench]]
name = "vin_bench"
harness = false

[[bench]]
name = "ractor_bench"
harness = false

[[bench]]
name = "coerce_bench"
harness = false

[[bench]]
name = "primitives_bench"
harness = false

[profile.bench]
opt-level = 3
codegen-units = 1
target-cpu = "native"
lto = true
overflow-checks = false
debug = false
