[package]
name = "praxis"
version = "0.1.0"
edition = "2021"

[dependencies]
praxis-derive = { path = "./praxis-derive", optional = true }
rayon = { version = "1.8.0", optional = true }
# pollster = { version = "0.3.0", optional = true }
ahash = "0.8"
async-trait = "0.1"
hashbrown = "0.14"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.32", features = ["full"] }
tracing = "0.1"
indexmap = "2.0.2"
rustc-hash = "1.1.0"
anyhow = "1.0.75"
flume = "0.11.0"
parking_lot = "0.12.1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
kanal = "0.1.0-pre8"
async-recursion = "1.0.5"
futures = "0.3.29"

[dev-dependencies]
praxis-derive = { path = "./praxis-derive" }
actix = "0.13.1"
vin = "9.1"
ractor = "0.9"
criterion = "0.5"
coerce = "0.8.10"

[features]
derive = ["dep:praxis-derive"]
rayon = ["dep:rayon"]

# [[bench]]
# name = "minions_bench"
# harness = false

[[bench]]
name = "tokio_bench"
harness = false

[[bench]]
name = "actix_bench"
harness = false

[[bench]]
name = "vin_bench"
harness = false

[[bench]]
name = "ractor_bench"
harness = false

[[bench]]
name = "coerce_bench"
harness = false

[[bench]]
name = "primitives_bench"
harness = false

[profile.bench]
opt-level = 3
codegen-units = 1
target-cpu = "native"
lto = true
overflow-checks = false
debug = false
