[package]
name = "ox_frame"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "self_call"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "1.0.0-beta.2"
async-trait = "0.1.73"
dashmap = "5.5.3"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
criterion = "0.5"
