name: Upload Coverage Reports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ribelo/pptr
